name: chat_ai_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  flutter_native_splash: ^2.4.8
  flutter_riverpod: ^2.6.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_app.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter_native_splash:
  color: "#3369FF"
  image: assets/images/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
